version: '3'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_savings}"
    image: localstack/localstack:0.12.6
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8060}:${PORT_WEB_UI-8060}"
