
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Include another YAML file
      - name: Include sub-workflow
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          path: |
            .github/workflows/maven.yml
