name: NGINX Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: test
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Pull NGINX image
        if: steps.test.outputs.cache-hit != 'true'
        run: docker pull nginx:latest

      - name: Run NGINX container
        run: docker run -d -p 8080:80 --name my-nginx nginx:latest

      - name: Deploy your application (replace with your deployment steps)
        run: |
          # Add your deployment steps here, e.g., copying your application files to the NGINX webroot.

      - name: Stop and remove NGINX container
        run: docker stop my-nginx && docker rm my-nginx
