name: savingsTest

on: push

jobs:
  savignsTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: restore-maven-cache
        uses: actions/cache/restore@v2
        with:
          path: ~/.cache
          key: setup-java-Linux-maven-${{ hashFiles('**/pom.xml') }}
          run: mvn -B package -DskipTests --file pom.xml
          
      - if: steps.restore-maven-cache.outputs.cache-hit != 'true'
        run: mvn -B package -DskipTests --file pom.xml
        
      - uses: actions/cache/save@v2
        with:
          path: ~/.cache
          key: ${{ steps.restore-maven-cache.outputs.cache-primary-key }}

        
