
name: Caching java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      # INSTALL JAVA
      - uses: actions/cache@v2
        id: cached-java
        with:
          path: |
            ~/.cache/java-11
            ~/.cache/maven1
          key: java 11.0.20.1
    
      - name: Install Java-11
        if: steps.cached-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk


      # INSTALL MAVEN
      - uses: actions/cache@v2
        id: cached-maven
        with:
          path: |
            ~/.cache/java-11
            ~/.cache/maven1
          key: Apache Maven 3.6.3
      - name: Install Maven
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
            sudo apt-get update -q
            sudo apt-get install -y maven

        
      # # Include another YAML file
      # - name: Include sub-workflow
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ github.repository }}
      #     ref: main
      #     path: |
      #       .github/workflows/maven.yml
