name: savingsTest

on: push

jobs:
  savignsTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: restore-maven-cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.cache/setup-java-Linux-maven-${{ hashFiles('**/pom.xml') }}
          key: setup-java-Linux-maven-${{ hashFiles('**/pom.xml') }}
          

      - uses: actions/cache/save@v3
        with:
          run: mvn -B package -DskipTests --file pom.xml
          path: ~/.cache/setup-java-Linux-maven-${{ hashFiles('**/pom.xml') }}
          key: ${{ steps.restore-maven-cache.outputs.cache-primary-key }}

        
